version: '3.1'

services:
  outsidetemp-service:
    build: ./outsidetemp
    volumes:
      - ./outsidetemp:/usr/src/app
    ports:
      - 5001:80

  ecobee-service:
    build: ./ecobeeapi
    volumes:
      - ./ecobeeapi:/usr/src/app
    ports:
      - 5002:80

  # docker run --cap-add=IPC_LOCK -e 'VAULT_DEV_ROOT_TOKEN_ID=myroot' -e 'VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:1234' vault
  # docker run --cap-add=IPC_LOCK -e 'VAULT_LOCAL_CONFIG={"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}' vault server
  vault:
    image: vault:latest
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
    ports:
      - 8200:8200
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_ADDRESS=http://0.0.0.0:8200
    command: vault server -config=/vault/config/vault.json

  #videocap:
  #  build: ./videocap_rtsp
  #  volumes:
  #    - ./videocap_rtsp:/usr/src/app
  #    - ./appdata:/appdata
  #    # -  
  #  environment:
  #    - CAPTURE_DURATION=10

  #eclipse-mosquitto:
  #  container_name: eclipse-mosquitto
  #  image: eclipse-mosquitto
  #  ports:
  #    - 1883:1883
  #    - 9001:9001
  #  volumes:
  #    - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  #    - ./mosquitto_passwd:/etc/mosquitto/passwd

  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    volumes:
      - ./homeassistant_config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "TZ=America/Montreal"
    restart: always
    network_mode: host
    ports:
      - "8123:8123"
    privileged: true

  influxdb:
    image: influxdb
    volumes:
      - influx:/var/lib/influxdb
    env_file:
      influxdb-variables.env
    #environment:
    #  INFLUXDB_ADMIN_USER: "FIX_ME"
    #  INFLUXDB_ADMIN_PASSWORD: "FIX_ME"
      # - INFLUXDB_USER: 
      # - INFLUXDB_USER_PASSWORD: 
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    restart: always

  telegraf:
    image: telegraf:1.6.1
    network_mode: "host"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - outsidetemp-service
      - ecobee-service

  grafana:
    image: grafana/grafana
    ports:
      - 0.0.0.0:3000:3000
    environment:
      GF_INSTALL_PLUGINS: "natel-discrete-panel"
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  influx:
    driver: local
  grafana:
    driver: local
  videocap:
    driver: local




