version: '3.1'

services:
  grafana:
    image: fg2it/grafana-armhf:v4.1.2

  homeassistant:
    image: homeassistant/raspberrypi3-homeassistant:latest
    logging:
        driver: "json-file"
        options:
            max-size: "50m"
  vault:
    image: vault
    #linux/arm/v6
volumes:
  grafana:
    driver: local


