- platform: mqtt
  name: busschedule_arrival_time
  state_topic: "schedule/bus_stop/32752/arrival_time"

- platform: mqtt
  name: busschedule_current_datetime
  state_topic: "schedule/bus_stop/32752/current_datetime"

- platform: mqtt
  name: busschedule_nextstop_nbrmins
  state_topic: "schedule/bus_stop/32752/nextstop_nbrmins"

- platform: mqtt
  name: busschedule_nextstop_nbrsecs
  state_topic: "schedule/bus_stop/32752/nextstop_nbrsecs"

- platform: mqtt
  name: busschedule_route_id
  state_topic: "schedule/bus_stop/32752/route_id"

- platform: mqtt
  name: busschedule_trip_headsign
  state_topic: "schedule/bus_stop/32752/trip_headsign"
