- platform: template
  sensors:
    prochain_arret:
      friendly_name: 'Bus Prochain Arrêt'
      value_template: > 
        dans {{ states('sensor.busschedule_nextstop_nbrmins') }}mins, {{ states('sensor.busschedule_nextstop_nbrsecs') }}secs
    bus_numero:
      friendly_name: 'Bus Numéro'
      value_template: > 
        bus {{ states('sensor.busschedule_route_id') }}
